"""Email delivery service using Resend."""

from __future__ import annotations

import logging
import textwrap

logger = logging.getLogger(__name__)


def send_report_email(
    *,
    to_email: str,
    user_name: str | None,
    query: str,
    final_report: str,
) -> bool:
    """Send the final research report by email via Resend.

    Returns True if the email was accepted, False on any error.
    """
    from api.config import settings  # local import avoids circular deps

    if not settings.resend_api_key:
        logger.warning("RESEND_API_KEY not set — skipping email delivery")
        return False

    try:
        import resend  # type: ignore[import-untyped]
    except ImportError:
        logger.error("resend package not installed — run `uv sync`")
        return False

    resend.api_key = settings.resend_api_key

    greeting = f"Hi {user_name}," if user_name else "Hi,"
    subject = f"Your research report: {textwrap.shorten(query, width=60, placeholder='…')}"

    html_body = _build_html(greeting, query, final_report)
    text_body = _build_text(greeting, query, final_report)

    try:
        resend.Emails.send(
            {
                "from": settings.email_from,
                "to": to_email,
                "subject": subject,
                "html": html_body,
                "text": text_body,
            }
        )
        logger.info("Report email sent to %s", to_email)
        return True
    except Exception:
        logger.exception("Failed to send report email to %s", to_email)
        return False


# ---------------------------------------------------------------------------
# HTML / plain-text helpers
# ---------------------------------------------------------------------------

def _md_to_simple_html(text: str) -> str:
    """Very light Markdown → HTML conversion (headers, bold, newlines).

    We avoid adding a full markdown library just for this.
    """
    import re

    lines: list[str] = []
    for line in text.splitlines():
        # H3 / H2 / H1
        if line.startswith("### "):
            lines.append(f"<h3>{line[4:]}</h3>")
        elif line.startswith("## "):
            lines.append(f"<h2>{line[3:]}</h2>")
        elif line.startswith("# "):
            lines.append(f"<h1>{line[2:]}</h1>")
        else:
            # Bold **text**
            line = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", line)
            lines.append(f"<p>{line}</p>" if line.strip() else "<br>")
    return "\n".join(lines)


def _build_html(greeting: str, query: str, report: str) -> str:
    report_html = _md_to_simple_html(report)
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <style>
    body {{ font-family: system-ui, sans-serif; color: #1a1a1a; max-width: 800px; margin: 0 auto; padding: 24px; }}
    h1, h2, h3 {{ color: #111; }}
    .query {{ background: #f4f4f5; border-left: 4px solid #6366f1; padding: 12px 16px; border-radius: 4px; margin: 16px 0; }}
    .footer {{ font-size: 12px; color: #71717a; margin-top: 40px; border-top: 1px solid #e4e4e7; padding-top: 16px; }}
  </style>
</head>
<body>
  <p>{greeting}</p>
  <p>Your Deep Researcher report is ready.</p>
  <div class="query"><strong>Research query:</strong> {query}</div>
  <hr>
  {report_html}
  <div class="footer">Generated by <strong>Deep Researcher</strong></div>
</body>
</html>"""


def _build_text(greeting: str, query: str, report: str) -> str:
    return f"""{greeting}

Your Deep Researcher report is ready.

Research query: {query}

{'=' * 60}

{report}

{'=' * 60}
Generated by Deep Researcher
"""
