OPENAI_GPT_4_1 = "gpt-4.1"
OPENAI_GPT_5 = "openai/gpt-5"
OPENAI_GPT_5_MINI = "gpt-5-mini"
OPENAI_GPT_5_NANO = "gpt-5-nano"

PROVIDER_OPENAI = "openai"
PROVIDER_AZURE_OPENAI = "azure_openai"
PROVIDER_GITHUB = "openai"

GITHUB_BASE_URL = "https://models.github.ai/inference"

SCOPE_MODEL_NAME = OPENAI_GPT_4_1
SCOPE_MODEL_PROVIDER = PROVIDER_GITHUB
SCOPE_MODEL_TEMPERATURE = 0.0

TEST_SCOPE_MODEL_NAME = OPENAI_GPT_4_1
TEST_SCOPE_MODEL_PROVIDER = PROVIDER_GITHUB
TEST_SCOPE_MODEL_TEMPERATURE = 0.0
