PRINT_SCOPE_GRAPH = False
SAVE_SCOPE_GRAPH = False

PRINT_RESEARCH_GRAPH = False
SAVE_RESEARCH_GRAPH = False

PRINT_SUPERVISOR_GRAPH = False
SAVE_SUPERVISOR_GRAPH = False

PRINT_WRITER_GRAPH = False
SAVE_WRITER_GRAPH = False